Mob 2028 jwt bindings
Iterable/react-native-sdk pull request #83
Opened 2020-10-13 18:46 UTC by davidtruong

[WIP] Starting the PR for the JWT on RN.

2020-10-13 20:21 UTC, tapashmajumder approved these changes
+1

This is a provisional +1. And only for iOS and React Native. I have not reviewed Android.

Jay please do not merge until you have tested JWT end to end.

2020-10-13 20:42 UTC, Ayyanchira commented on android/build.gradle
> +    api 'com.github.Iterable.iterable-android-sdk:iterableapi:3.2.7-beta2'
Need changes to accommodate the latest GA build

2020-10-13 22:07 UTC, vbabenkoru requested changes

2020-10-13 22:07 UTC, vbabenkoru commented on android/src/main/java/com/iterable/reactnative/RNIterableAPIModule.java
> +            authHandlerCallbackLatch.await(30, TimeUnit.SECONDS);
@roninopf It looks like we don't actually call `.countDown()` on the latch anywhere, so it'll always just wait for 30 seconds.

2020-10-13 22:08 UTC, Ayyanchira approved these changes
Looks good.. 🤞
Lets merge and test it out!!!

2020-10-13 22:11 UTC, vbabenkoru commented on android/src/main/java/com/iterable/reactnative/RNIterableAPIModule.java
> +        passedAuthToken = authToken;
Need to add something like this here
```
if (authHandlerCallbackLatch != null) {
    authHandlerCallbackLatch.countDown();
}
```

Similar to what we do in `setInAppShowResponse`.

2020-10-13 22:16 UTC, vbabenkoru commented on ts/Iterable.ts
> +  authTokenRequestedHandler?: () => Promise<string | undefined>
This is called `authHandler`/`authDelegate` in native SDKs. Is there a reason to have a different name here?

2020-10-13 23:23 UTC, vbabenkoru approved these changes
Code looks good! Haven't tested this since the dev app crashes on my emulator for some reason.

2020-10-14 00:34 UTC, vbabenkoru commented on package.json
> +  "version": "1.0.14-beta1",
```suggestion
  "version": "1.0.14",
```

2020-10-14 00:35 UTC, vbabenkoru approved these changes
:shipit:

2020-10-14 00:41 UTC, merged